08 polymorphism
upl1nk-v01d/clx_csharp pull request #11
Opened 2024-09-10 15:25 UTC by upl1nk-v01d

2024-09-13 09:13 UTC, Latviets approved these changes

2024-09-16 10:42 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/AdApp/Hoarding.cs
>          public new int Cost()
kapēc new? varbūt override labāk?

2024-09-16 10:46 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Firm/StaffMember.cs
> +        public virtual void AddSales(int sales)
varbūt abstract?

2024-09-16 10:49 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public virtual void makeSound()
abstract?

2024-09-16 10:49 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public string eat(Food food)
```suggestion
        public string Eat(Food food)
```

2024-09-16 10:50 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public string eat(Food food)
vispār abstract šajā punktā es teiktu. :)

2024-09-16 10:50 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/MammalFelimeTiger.cs
> +        public override void makeSound()
```suggestion
        public override void MakeSound()
```

2024-09-16 10:50 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/MammalMouse.cs
> +        public string _sound = "peeek";
```suggestion
        public string Sound = "peeek";
```

2024-09-16 10:51 UTC, EdgarsSalmins requested changes
formatings.. namings. :) etc... pārrskati visu.. 
ja pielikšu pie katras vietas komentāru būs kādi 100 komentāri. :D

2024-09-24 04:04 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public string _animalName;
public prop namings cits. :)

2024-09-24 04:04 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/VendingMachine/Program.cs
> +            VendingMachine vendingMachine = new VendingMachine("Coke", 100, 50);
```suggestion
            IVendingMachine vendingMachine = new VendingMachine("Coke", 100, 50);
```

2024-09-24 04:05 UTC, EdgarsSalmins approved these changes

2024-09-26 09:03 UTC, merged