02 arithmetics completed
upl1nk-v01d/clx_csharp pull request #5
Opened 2024-08-18 16:32 UTC by upl1nk-v01d

section's 'Arithmetic' exercises are completed (phew!).

2024-08-18 17:51 UTC, Latviets approved these changes
Varbūt tā šķiet tikai man kā pilnīgam iesācējam, bet tādas diezgan sarežģītas funkcijas veido priekš šādiem vienkāršiem uzdevumiem. :D

2024-08-18 17:51 UTC, Latviets commented on csharp-basics/exercises/Arithmetic/exc01/Program.cs
Diezgan sarežģīta sistēma ļoti vienkāršam uzdevumam. :D

2024-08-21 06:50 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/SumAverageRunningInt/Program.cs
> +                sum += number; c++;
```suggestion
                sum += number; 
                c++;
```

2024-08-21 06:52 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc01/Program.cs
> +        int num1=0, num2=0;
```suggestion
        var num1=0; 
        var num2=0;
```

2024-08-21 06:52 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc01/Program.cs
> +            if(!err){
```suggestion
            if(!err)
            { 
```

2024-08-21 06:52 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc01/Program.cs
> +        while(!quit){
```suggestion
        while(!quit)
        {
```

2024-08-21 06:52 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc01/Program.cs
> +            if(sw == 0){
```suggestion
            if(sw == 0)
            {
```

2024-08-21 06:52 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc01/Program.cs
> +                }
tukša rinda aiz }

2024-08-21 06:54 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc06/Program.cs
> +                sleep(2000);
priekš kam sleep?

2024-08-21 06:54 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc06/Program.cs
> +    static void sleep(int delay=1){
```suggestion
    static void Sleep(int delay=1){
```

2024-08-21 06:54 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc06/Program.cs
> +    static void displayText(string text, int delay=30){
```suggestion
    static void DisplayText(string text, int delay=30){
```

2024-08-21 06:54 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc06/Program.cs
> +    static void displayTextArray(string[] text, int delay=30){
```suggestion
    static void DisplayTextArray(string[] text, int delay=30){
```

2024-08-21 06:54 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc06/Program.cs
> +    }
tukša rinda pietrūkst

2024-08-21 06:54 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc06/Program.cs
> +    static void Main(string[] args){
starp metodēm vienmēr tukša rinda

2024-08-21 06:55 UTC, EdgarsSalmins requested changes
nosaukumi jāsalabo visur... 
formatējums jāsalabo visur.. 
kopumā šķiet ka overengeneering priekš tik triviāliem uzdevumiem

2024-08-21 10:06 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc02/Program.cs
>              retry=false;
retry = false;

2024-08-21 10:07 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc02/Program.cs
> +
lieka tukša rinda? if else it kopā? tapēc starpā tukšu rindu nevajag?

2024-08-21 10:07 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc05/Program.cs
>              if(sw == 0){
{ jaunā rindā.

2024-08-21 10:09 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc06/Program.cs
> +                sleep(2000);
?

2024-08-21 14:50 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/exc01/Program.cs
> +                //using abs function to return absolute value
vajag to komentāru? viņā tiešām ir kāda pievienotā vērtība?

2024-08-21 15:11 UTC, EdgarsSalmins approved these changes

2024-08-21 17:09 UTC, merged