03 flow control
upl1nk-v01d/clx_csharp pull request #6
Opened 2024-08-19 11:40 UTC by upl1nk-v01d

all section's 'Flow Control' exercises are done.
note: on exercise GetTheCentury wrong commit message, should be committed as exercise 06.

2024-08-19 11:50 UTC, Janchuks approved these changes

2024-08-19 19:16 UTC, Latviets approved these changes

2024-08-19 19:16 UTC, Latviets commented on csharp-basics/exercises/FlowOfControl/TenBillion/Program.cs
It kā nemanu kur tiktu veikta šī daļa: count the number of digits the number (...) has.

2024-08-19 19:54 UTC, Janchuks commented on csharp-basics/exercises/FlowOfControl/GetTheCentury/Program.cs
You had some spare time to check for all the options. Super impressed !!

2024-08-19 19:56 UTC, Janchuks commented on csharp-basics/exercises/FlowOfControl/PositiveNegativeNumber/Program.cs
> +            else if (double.Parse(input) < 0){
Why did you do the parsing to double?

2024-08-19 19:57 UTC, Janchuks commented on csharp-basics/exercises/FlowOfControl/exc04/Program.cs
> +                displayText("wtf? Please only a digit!");
bahahahahahaha!! "wtf?" has me chuckling

2024-08-19 19:58 UTC, Janchuks commented on csharp-basics/exercises/FlowOfControl/exc05/Program.cs
This one was funny! Love itt!!

2024-08-19 19:59 UTC, Janchuks commented on csharp-basics/exercises/FlowOfControl/exc07/Program.cs
> +    static void displayText(string text="\n", int tick=30, int el=1, int delay=0){
Im lost.. What does the int el represent?

2024-08-19 20:01 UTC, Janchuks approved these changes
10/10. Some bits were super funny, which is totally adorable and made me smile. :))

2024-08-21 07:15 UTC, EdgarsSalmins requested changes
tas pats kas citos citos PR.. :) jāsataisa formatējums.. nosaukumi jāsalbo.. :)

2024-08-21 14:47 UTC, EdgarsSalmins commented on csharp-basics/exercises/FlowOfControl/GetTheCentury/Program.cs
> +
```suggestion
```

2024-08-21 14:47 UTC, EdgarsSalmins commented on csharp-basics/exercises/FlowOfControl/GetTheCentury/Program.cs
> +
šis uz visiem else if attiecas jo if un else if ir saistītas lietas. :)

2024-08-21 14:47 UTC, EdgarsSalmins commented on csharp-basics/exercises/FlowOfControl/LargestNumber/Program.cs
> +            return largestNumber;
```suggestion

            return largestNumber;
```

2024-08-21 14:48 UTC, EdgarsSalmins commented on csharp-basics/exercises/FlowOfControl/exc04/Program.cs
> +                Sleep(1000);
kam Tev tas sleep ir vajadzīgs?

2024-08-21 14:48 UTC, EdgarsSalmins reviewed
man tas sleep sāk ļoti interesēt.. priekš kam? visos darbos redzu.

2024-08-21 15:12 UTC, EdgarsSalmins approved these changes

2024-08-21 17:09 UTC, merged