section 'Classes & Objects' is completed.
upl1nk-v01d/clx_csharp pull request #9
Opened 2024-08-30 13:32 UTC by upl1nk-v01d

Exercises of section 'Classes & Objects' are completed.

2024-08-30 14:19 UTC, Latviets approved these changes

2024-09-03 08:23 UTC, EdgarsSalmins commented on csharp-basics/exercises/ClassesAndObjects/BankAccount/Program.cs
> +        public string Name { get; set; }
varbūt vismaz private set? lai Tavs maciņš nekļūst par kāda cita maciņu?

2024-09-03 08:24 UTC, EdgarsSalmins commented on csharp-basics/exercises/ClassesAndObjects/BankAccount/Program.cs
> +        public double Balance { get; set; }
ne līdz galam šī mainīgā jēgu saprotu?

2024-09-03 08:27 UTC, EdgarsSalmins commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/Program.cs
> +        private static readonly VideoStore store = new VideoStore();
```suggestion
        private static readonly VideoStore _store = new VideoStore();
```

2024-09-03 08:27 UTC, EdgarsSalmins commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/Program.cs
> +            var _store = store.ListInventory();
```suggestion
            var inventory = store.ListInventory();
```

2024-09-03 08:29 UTC, EdgarsSalmins commented on csharp-basics/exercises/ClassesAndObjects/exc01/ClassProductList.cs
> +    public string Name { get; set; }
Šie visi prop ir private. :) 
pēc uzdevuma vismaz. :) 
un tad ir vajadzīgs konstruktors. :) 
un kas attiecas uz daudzuma maiņu un cenas maiņu tur bija vajadzīgas metodes.

2024-09-03 08:43 UTC, EdgarsSalmins requested changes
ir dažas lietas jāpalabo. :)

2024-09-04 06:12 UTC, EdgarsSalmins commented on csharp-basics/exercises/ClassesAndObjects/exc03/ClassCarOdometer.cs
> +    public string CarName { get; set; }
```suggestion
    public string CarName { get; private set; }
```

2024-09-04 06:12 UTC, EdgarsSalmins approved these changes

2024-09-04 06:13 UTC, EdgarsSalmins commented on csharp-basics/exercises/ClassesAndObjects/Account/Account.cs
> +        public string _name { get; set; }
```suggestion
        private string _name { get; set; }
```

2024-09-04 06:13 UTC, EdgarsSalmins commented on csharp-basics/exercises/ClassesAndObjects/BankAccount/Program.cs
> +        private string Name { get; set; }
```suggestion
        private string _name { get; set; }
```

2024-09-04 06:13 UTC, EdgarsSalmins commented on csharp-basics/exercises/ClassesAndObjects/BankAccount/Program.cs
> +        private double Balance { get; set; }
```suggestion
        private double _balance { get; set; }
```

2024-09-04 06:13 UTC, EdgarsSalmins approved these changes

2024-09-26 09:01 UTC, merged